api_platform:
  eager_loading:
    enabled: true
    fetch_partial: false
    max_joins: 30
    force_eager: false

  formats:
    jsonld: [ 'application/ld+json' ]
    json: [ 'application/json']
    html: [ 'text/html' ]
    jsonhal: [ 'application/hal+json' ]
    jonsmerge: ['application/merge-patch+json']
    multipart: ['multipart/form-data']

  swagger:
    api_keys:
      access_token:
        name: Authorization
        type: header


#    enable_docs: false
#    enable_entrypoint: false
#    enable_swagger: false
#    enable_swagger_ui: false
