vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        user_pic:
            uri_prefix: uploads/pictures/users/profiles
            upload_destination: '%kernel.project_dir%/public/uploads/pictures/profiles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer