vich_uploader:
    db_driver: orm

    mappings:
        user_picture:
            uri_prefix: /pictures/users/profiles
            upload_destination: '%kernel.project_dir%/public/pictures/users/profiles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
